spring:
  application:
    name: GATEWAY-SERVICE

server:
  port: 9000



zuul:
   routes:
     user-service:
#       path: /users/**
       uri: lb://user-service



     package-service:
        path: /package/**
        uri: lb://package-service